<a href="https://colab.research.google.com/github/mojahid-t17/BasicPython-note/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#istall numpy: !pip install  numpy
#list import different data type but in array only can impoprt same data type
#list can not do mathmatical operation but in numpy we can do that
a=[4,'list',34.5]
print(a)
lst_1= [1,2,3]
lst_2=[34,23,3]
print(lst_1+lst_2)

import numpy as np
arr_1=np.array([1,2,3])
arr_2=np.array([34,23,3])
print(arr_1+arr_2)

[4, 'list', 34.5]
[1, 2, 3, 34, 23, 3]
[35 25  6]


In [ ]:
import numpy as np

#create numpy array by passing list
a= np.array([2,3,4])
# create array by passing touple
b=np.array((1,2,3))
print(a)
print(b)
print(type(a))


[1, 2, 3, 34, 23, 3]
[2 3 4]
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#array dimention:

#/// 0 dimention
import numpy as np
a=np.array(34)
print("dimention of a ",a.ndim)

# /// 1 dimention
b= np.array([1,2,3])
print("dimention of b ",b.ndim)

# 2 dimention
c=np.array([[1,2,3],[4,5,6]])
# print(c)
print("dimention of c ",c.ndim)

dimention of a  0
dimention of b  1
dimention of c  2


In [ ]:
#array slicing :
import numpy as np

arr=np.array([[20,30,40,50],[60,70,80,90],[10,30,34,20]])
# print(arr)
print(arr[0])
print(arr[0:2])
print("the selected second row elemnts",arr[1,1:3])


[20 30 40 50]
[[20 30 40 50]
 [60 70 80 90]]
the second row elemnt [70 80]


In [ ]:
#find the row colomn of a matrix
import numpy as np

arr=np.array([[20,30,40,50],[60,70,80,90],[10,30,34,20]])
print(np.shape(arr))

print("reshape the matrix 3 X 4")
print(arr.reshape(4,3))
#total element
# print(np.size(arr))
print(arr.size)
print(arr.dtype)
#convert data type
print(arr.astype(str))

(3, 4)
reshape the matrix 3 X 4
[[20 30 40]
 [50 60 70]
 [80 90 10]
 [30 34 20]]
12
int64
[['20' '30' '40' '50']
 ['60' '70' '80' '90']
 ['10' '30' '34' '20']]


In [ ]:
import numpy as np

#concetenate array
arr_1=np.array([10,20,30])
arr_2=np.array([34,23,3])
print(np.concatenate([arr_1,arr_2]))



[10 20 30 34 23  3]
[[20 30 40]
 [60 70 80]
 [10 30 34]
 [ 5 15 25]
 [ 4 14 24]
 [ 9 99 19]]


In [ ]:
# concatenaete 2 matrix horizontally (x axis)

arr1=np.array([[20 ,30, 40 ],[60, 70, 80 ],[10, 30 ,34]])
arr2=np.array([[5,15,25],[4,14,24],[9,99,19]])

print(np.concatenate([arr1,arr2],axis=1))
print("\n",np.hstack([arr1,arr2]))

[[20 30 40  5 15 25]
 [60 70 80  4 14 24]
 [10 30 34  9 99 19]]

 [[20 30 40  5 15 25]
 [60 70 80  4 14 24]
 [10 30 34  9 99 19]]


In [ ]:
#vertical concatenate:
# concatenaete 2 matrix vertically (y axis)
import numpy as np

arr1=np.array([[20 ,30, 40 ],[60, 70, 80 ],[10, 30 ,34]])
arr2=np.array([[5,15,25],[4,14,24],[9,99,19]])

# print(np.concatenate([arr1,arr2],axis=0))
print(np.vstack([arr1,arr2]))

[[20 30 40]
 [60 70 80]
 [10 30 34]
 [ 5 15 25]
 [ 4 14 24]
 [ 9 99 19]]


In [ ]:
#array split
import numpy as np
x=np.array([1,2,3,4,5,6,7,8])
arr=np.array([[20,30,40,50],[60,70,80,90],[10,30,34,20]])
print(np.array_split(arr,2))

y=np.array_split(x,3)
print(y)
print(y[1])

[array([[20, 30, 40, 50],
       [60, 70, 80, 90]]), array([[10, 30, 34, 20]])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[4 5 6]


In [ ]:
#generate number by np
import numpy as np

print(np.arange(20))

#we can define the differnce the number:

print(np.arange(1,20,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
#create matrix by zero or one

print(np.zeros((2,3)))

print(np.ones((2,3)))

#create random number

print(np.random.random((1,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.31144142 0.15451292 0.21404593]]


In [ ]:
#linearly spaced array: provide the linear difference array between a range
#first two parameter is the range and lst is the total number of item that you want between this range

import numpy as np

print(np.linspace(-2,10,5))

[-2.  1.  4.  7. 10.]


In [ ]:
#create identity matrix:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.arange(1,13).reshape(4,3)
arr=a*10

print(arr)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [ ]:
import numpy as np
np.max(arr)

# find the  largest item of all colomn
np.max(arr,axis=0)
#find the largest item of all row

np.max(arr,axis=1)

array([ 20,  50,  80, 110])

In [ ]:
np.min(arr)
# find the product of all elements
x=np.array([[1,2,3],[4,5,6]])
np.prod(x)

# dot product of two matrix /m x n * n x c = m x c
a1=np.arange(12).reshape(4,3)
a2=np.arange(13,25).reshape(3,4)
print(np.dot(a1,a2))

[[ 59  62  65  68]
 [212 224 236 248]
 [365 386 407 428]
 [518 548 578 608]]


In [ ]:
# find the log and exponential of all elements
x1=np.log(a2)
print(x1)
x2=np.exp(a2)
print(x2)

[[2.56494936 2.63905733 2.7080502  2.77258872]
 [2.83321334 2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422 3.17805383]]
[[4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06]
 [2.41549528e+07 6.56599691e+07 1.78482301e+08 4.85165195e+08]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09 2.64891221e+10]]


In [ ]:
#find the floor cell and round value

print(np.ceil(x1))
print(np.floor(x1))
print(np.round(x1))

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
